site_name: Bodhi Mobile Application Development
pages:
- ['GettingStarted.md', 'Getting Started']
- ['HowToGuide.md', 'How To Guide']
- ['BodhiMobileApplicationTools/MobileApps.md', 'Bodhi Mobile Application Tools', 'Bodhi App Tools']
- ['BodhiMobileAPI/MobileContainer.md', 'Home']
- ['BodhiMobileAPI/appStorage.md', 'Bodhi Mobile API', 'AppStorage']
- ['BodhiMobileAPI/archiving.md', 'Bodhi Mobile API', 'Archiving']
- ['BodhiMobileAPI/audio.md', 'Bodhi Mobile API', 'Audio']
- ['BodhiMobileAPI/audioItem.md', 'Bodhi Mobile API', 'Audio Item']
- ['BodhiMobileAPI/authentication.md', 'Bodhi Mobile API', 'Authentication']
- ['BodhiMobileAPI/barcode.md', 'Bodhi Mobile API', 'Barcode']
- ['BodhiMobileAPI/battery.md', 'Bodhi Mobile API', 'Battery']
- ['BodhiMobileAPI/btPeripheral.md', 'Bodhi Mobile API', 'Bluetooth Peripheral']
- ['BodhiMobileAPI/calendar.md', 'Bodhi Mobile API', 'Calendar']
- ['BodhiMobileAPI/camera.md', 'Bodhi Mobile API', 'Camera']
- ['BodhiMobileAPI/compass.md', 'Bodhi Mobile API', 'Compass']
- ['BodhiMobileAPI/connection.md', 'Bodhi Mobile API', 'Connection']
- ['BodhiMobileAPI/connectionMonitor.md', 'Bodhi Mobile API', 'Connection Monitor']
- ['BodhiMobileAPI/contacts.md', 'Bodhi Mobile API', 'Contacts']
- ['BodhiMobileAPI/cryptography.md', 'Bodhi Mobile API', 'Cryptography']
- ['BodhiMobileAPI/device.md', 'Bodhi Mobile API', 'Device']
- ['BodhiMobileAPI/deviceOrientation.md', 'Bodhi Mobile API', 'Device Orientation']
- ['BodhiMobileAPI/globalization.md', 'Bodhi Mobile API', 'Globalization']
- ['BodhiMobileAPI/iBeacon.md', 'Bodhi Mobile API', 'iBeacon']
- ['BodhiMobileAPI/kernel_errors.md', 'Bodhi Mobile API', 'Kernel Errors']
- ['BodhiMobileAPI/kernel_events.md', 'Bodhi Mobile API', 'Kernel Events']
- ['BodhiMobileAPI/kernel_promise.md', 'Bodhi Mobile API', 'Kernel Promise']
- ['BodhiMobileAPI/launch.md', 'Bodhi Mobile API', 'Launch']
- ['BodhiMobileAPI/localnotifications.md', 'Bodhi Mobile API', 'Local Notifications']
- ['BodhiMobileAPI/mainMenu.md', 'Bodhi Mobile API', 'Main Menu']
- ['BodhiMobileAPI/messaging.md', 'Bodhi Mobile API', 'Messaging']
- ['BodhiMobileAPI/navigationBar.md', 'Bodhi Mobile API', 'Navigation Bar']
- ['BodhiMobileAPI/notifications.md', 'Bodhi Mobile API', 'Notifications']
- ['BodhiMobileAPI/printing.md', 'Bodhi Mobile API', 'Printing']
- ['BodhiMobileAPI/pushNotifications.md', 'Bodhi Mobile API', 'Push Notifications']
- ['BodhiMobileAPI/webview.md', 'Bodhi Mobile API', 'Webview']
- ['Security.md', 'Security']
theme: readthedocs
