site_name: RBC Platform Documentation
pages:
- ['index.md', 'Home']
- ['GettingStarted.md', 'Getting Started']
- ['Agent.md', 'Agent']
- ['AgentApps.md', 'Writing Agent Apps']
- ['MobileApps.md', 'Writing Mobile Apps']
- ['MobileContainer.md', 'Mobile Container API']
- ['API.md', 'Platform API']
- ['Security.md', 'Security']
- ['rbc-cli.md', 'Tools']
theme: readthedocs
