site_name: RBC Platform Documentation
pages:
- ['index.md', 'Home']
- ['GettingStarted.md', 'Getting Started']
- ['Agent.md', 'Agent']
- ['./AgentApps/Extensions.md', 'Writing Agent Apps']
- ['MobileApps.md', 'Writing Mobile Apps']
- ['Security.md', 'Security']
- ['rbc-cli.md', 'Tools']
- ['API.md', 'Platform API']
- ['./Mobile API/MobileContainer.md', 'Mobile API']
- ['./Mobile API/appStorage.md', 'AppStorage']
theme: readthedocs
