site_name: RBC Platform Documentation
pages:
- ['index.md', 'Home']
- ['GettingStarted/index.md', 'Getting Started']
- ['Agent/index.md', 'Agent']
- ['AgentApps/index.md', 'Agent Apps']
- ['MobileContainer/index.md', 'Mobile Container']
- ['MobileApps/index.md', 'Mobile Apps']
- ['Platform/index.md', 'Platform']
- ['Security/index.md', 'Security']
- ['Tools/index.md', 'Tools']
- ['Tools/rbc-cli.md', 'Tools']
theme: readthedocs
