site_name: RBC Platform Documentation
pages:
- ['index.md', 'Home']
- ['GettingStarted.md', 'Getting Started']
- ['Agent.md', 'Agent']
- ['./AgentApps/Extensions.md', 'Writing Agent Apps']
- ['MobileApps.md', 'Writing Mobile Apps']
- ['Security.md', 'Security']
- ['rbc-cli.md', 'Tools']
- ['API.md', 'Platform API']
- ['./Mobile API/MobileContainer.md', 'Mobile API']
- ['./Mobile API/appStorage.md', 'Mobile API', 'AppStorage']
- ['./Mobile API/archiving.md', 'Mobile API', 'Archiving']
- ['./Mobile API/audio.md', 'Mobile API', 'Audio']
- ['./Mobile API/audioItem.md', 'Mobile API', 'Audio Item']
- ['./Mobile API/authentication.md', 'Mobile API', 'Authentication']
- ['./Mobile API/barcode.md', 'Mobile API', 'Barcode']
- ['./Mobile API/battery.md', 'Mobile API', 'Battery']
- ['./Mobile API/btPeripheral.md', 'Mobile API', 'Bluetooth Peripheral']
- ['./Mobile API/calendar.md', 'Mobile API', 'Calendar']
- ['./Mobile API/camera.md', 'Mobile API', 'Camera']
- ['./Mobile API/compass.md', 'Mobile API', 'Compass']
- ['./Mobile API/connection.md', 'Mobile API', 'Connection']
- ['./Mobile API/connectionMonitor.md', 'Mobile API', 'Connection Monitor']
- ['./Mobile API/contacts.md', 'Mobile API', 'Contacts']
- ['./Mobile API/cryptography.md', 'Mobile API', 'Cryptography']
- ['./Mobile API/device.md', 'Mobile API', 'Device']
- ['./Mobile API/deviceOrientation.md', 'Mobile API', 'Device Orientation']
- ['./Mobile API/globalization.md', 'Mobile API', 'Globalization']
- ['./Mobile API/iBeacon.md', 'Mobile API', 'iBeacon']
- ['./Mobile API/kernel_errors.md', 'Mobile API', 'Kernel Errors']
- ['./Mobile API/kernel_events.md', 'Mobile API', 'Kernel Events']
- ['./Mobile API/kernel_promise.md', 'Mobile API', 'Kernel Promise']
- ['./Mobile API/launch.md', 'Mobile API', 'Launch']
- ['./Mobile API/localnotifications.md', 'Mobile API', 'Local Notifications']
- ['./Mobile API/mainMenu.md', 'Mobile API', 'Main Menu']
- ['./Mobile API/messaging.md', 'Mobile API', 'Messaging']
- ['./Mobile API/navigationBar.md', 'Mobile API', 'Navigation Bar']
- ['./Mobile API/notifications.md', 'Mobile API', 'Notifications']
- ['./Mobile API/printing.md', 'Mobile API', 'Printing']
- ['./Mobile API/pushNotifications.md', 'Mobile API', 'Push Notifications']
- ['./Mobile API/webview.md', 'Mobile API', 'Webview']
theme: readthedocs
