site_name: RBC Platform Documentation
pages:
- ['MobileContainer.md', 'Home']
- ['appStorage.md', 'Mobile API', 'AppStorage']
- ['archiving.md', 'Mobile API', 'Archiving']
- ['audio.md', 'Mobile API', 'Audio']
- ['audioItem.md', 'Mobile API', 'Audio Item']
- ['authentication.md', 'Mobile API', 'Authentication']
- ['barcode.md', 'Mobile API', 'Barcode']
- ['battery.md', 'Mobile API', 'Battery']
- ['btPeripheral.md', 'Mobile API', 'Bluetooth Peripheral']
- ['calendar.md', 'Mobile API', 'Calendar']
- ['camera.md', 'Mobile API', 'Camera']
- ['compass.md', 'Mobile API', 'Compass']
- ['connection.md', 'Mobile API', 'Connection']
- ['connectionMonitor.md', 'Mobile API', 'Connection Monitor']
- ['contacts.md', 'Mobile API', 'Contacts']
- ['cryptography.md', 'Mobile API', 'Cryptography']
- ['device.md', 'Mobile API', 'Device']
- ['deviceOrientation.md', 'Mobile API', 'Device Orientation']
- ['globalization.md', 'Mobile API', 'Globalization']
- ['iBeacon.md', 'Mobile API', 'iBeacon']
- ['kernel_errors.md', 'Mobile API', 'Kernel Errors']
- ['kernel_events.md', 'Mobile API', 'Kernel Events']
- ['kernel_promise.md', 'Mobile API', 'Kernel Promise']
- ['launch.md', 'Mobile API', 'Launch']
- ['localnotifications.md', 'Mobile API', 'Local Notifications']
- ['mainMenu.md', 'Mobile API', 'Main Menu']
- ['messaging.md', 'Mobile API', 'Messaging']
- ['navigationBar.md', 'Mobile API', 'Navigation Bar']
- ['notifications.md', 'Mobile API', 'Notifications']
- ['printing.md', 'Mobile API', 'Printing']
- ['pushNotifications.md', 'Mobile API', 'Push Notifications']
- ['webview.md', 'Mobile API', 'Webview']
theme: readthedocs
